default_platform(:android)

platform :android do
  service_credentials_file = "/Volumes/Data/source_projects/react_native/ExampleJenkins/fastlane/example-jenkins-6a6451ed48a4.json"

  desc "Building App for Dev"
  lane :develop do |options|
    begin
    desc "Building APK...."
    gradle(
      task: "assemble",
      flavor: "Dev",
      build_type: "Release",
      properties: {
          "android.injected.version.code" => 1,
          "android.injected.version.name" => "1.0.0",
        }
    )
    desc "Building Done...."
    firebase_app_distribution(
      app: "1:611912278358:android:8d8c7a5e7bbd1a3784b6f7",
      service_credentials_file: service_credentials_file,
      release_notes: "Lots of amazing new features to test out!"
    )
    rescue => exception
        UI.error(exception)
    end
  end
  desc "Building App for Staging"
  lane :staging do |options|
    begin
    desc "Building APK...."
    increment_version_code(
      gradle_file_path: "../android/app/build.gradle",
      version_code: ENV["CI_BUILD_ID"]
    )
    increment_version_name(
      gradle_file_path: "../android/app/build.gradle",
      version_name: "1.0.1"
    )
    gradle(task: "clean")
    gradle(
      task: "assemble",
      flavor: "Stg",
      build_type: "Release"
    )
    desc "Building Done...."
    firebase_app_distribution(
      app: "1:611912278358:android:0727dad3e0bafe7a84b6f7",
      service_credentials_file: service_credentials_file,
      release_notes: "Lots of amazing new features to test out!"
    )
    rescue => exception
        UI.error(exception)
    end
  end

  desc "Building App for UAT"
  lane :uat do |options|
    begin
    desc "Building APK...."
    gradle(
      task: "assemble",
      flavor: "Uat",
      build_type: "Release",
      properties: {
          "android.injected.version.code" => 1,
          "android.injected.version.name" => "1.0.0",
        }
    )
    desc "Building Done...."
    firebase_app_distribution(
      app: "1:611912278358:android:9cde9b498277111484b6f7",
      service_credentials_file: service_credentials_file,
      release_notes: "Lots of amazing new features to test out!"
    )
    rescue => exception
        UI.error(exception)
    end
  end

  desc "Building App for PROD"
  lane :prod do |options|
    begin
    desc "Building APK...."
    gradle(
      task: "assemble",
      flavor: "Prod",
      build_type: "Release",
      properties: {
          "android.injected.version.code" => 1,
          "android.injected.version.name" => "1.0.0",
        }
    )
    desc "Building Done...."
    firebase_app_distribution(
      app: "1:611912278358:android:068c01757459175f84b6f7",
      service_credentials_file: service_credentials_file,
      release_notes: "Lots of amazing new features to test out!"
    )
    rescue => exception
        UI.error(exception)
    end
  end
end
