# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Building App for Dev"
  lane :develop do |options|
    begin

    desc "Building...."
    sh "./app_build.sh --android"
    desc "Building Done...."
    rescue => exception
    on_error(exception)
    end
  end

  desc "Building App for Staging"
  lane :staging do |options|
    begin

    desc "Building...."
    sh "../../fastlane/app_build.sh --android"
    desc "Building Done...."
    release = firebase_app_distribution(
                app: "1:123456789:android:abcd1234",
                testers: "tester1@company.com, tester2@company.com",
                release_notes: "Lots of amazing new features to test out!"
            )
    rescue => exception
    on_error(exception)
    end
  end

  desc "Building App for UAT"
  lane :uat do |options|
    begin

    desc "Building...."
    sh "./app_build.sh --android"
    desc "Building Done...."
    rescue => exception
    on_error(exception)
    end
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleStgRelease")
    crashlytics

    sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
